development:
  adapter: postgresql
  encoding: unicode
  database: theleague_development
  pool: 5
  username: theleague
  password: hunter
  
test:
  adapter: postgresql
  encoding: unicode
  database: theleague_test
  pool: 5
  username: theleague
  password: hunter
